### ISSUE TITLE
attribute '_SelectableIcon__super' missing

### ISSUE THREAD

**Issue by ttanner** [urwid/urwid#110]
On OSX with Python 3.4.2:

$ python3.4 -c "import urwid"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$path/urwid/__init__.py", line 36, in <module>
    from urwid.wimp import (SelectableIcon, CheckBoxError, CheckBox, RadioButton,
  File "$path/urwid/wimp.py", line 99, in <module>
    class CheckBox(WidgetWrap):
  File "$path/urwid/wimp.py", line 104, in CheckBox
    True: SelectableIcon("[X]"),
  File "$path/urwid/wimp.py", line 47, in __init__
    self.__super.__init__(text)
AttributeError: 'SelectableIcon' object has no attribute '_SelectableIcon__super'
```

**Comment by jrmiller82** [comment]
Same Issue here:

    % python3 main.py
    Traceback (most recent call last):
    File "main.py", line 1, in <module>
    import urwid
    File "/Storage/lhx/private_repos/urwid-test/urwid/__init__.py", line 36, in <module>
    from urwid.wimp import (SelectableIcon, CheckBoxError, CheckBox, RadioButton,
    File "/Storage/lhx/private_repos/urwid-test/urwid/wimp.py", line 99, in <module>
    class CheckBox(WidgetWrap):
    File "/Storage/lhx/private_repos/urwid-test/urwid/wimp.py", line 104, in CheckBox
    True: SelectableIcon("[X]"),
    File "/Storage/lhx/private_repos/urwid-test/urwid/wimp.py", line 47, in __init__
    self.__super.__init__(text)
    AttributeError: 'SelectableIcon' object has no attribute '_SelectableIcon__super'

And here's main.py:
    
    import urwid

    def main():
        txt = urwid.Text(u"Hello World")
        fill = urwid.Filler(txt, 'top')
        loop = urwid.MainLoop(fill)
        loop.run()

    if __name__ == "__main__":
        main()

And my version of Python3:

    % python3
    Python 3.5.0 (default, Sep 20 2015, 11:28:25)
    [GCC 5.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>>

**Comment by wardi** [comment]
It's past time to remove the __super hack. Any volunteers?

**Comment by ttanner** [comment]
https://github.com/wardi/urwid/issues/111 removes __super.

**Comment by eevee** [comment]
From what I can tell, `__super` works just fine in Python 3.  It just doesn't work in a clean checkout of urwid, because it's still relying on 2to3, so the metaclass that adds `__super` is missing.
