### ISSUE TITLE
urwid escape.py crashes in process_keyqueue while attempting to process mouse event

### ISSUE THREAD

**Issue by doddo** [urwid/urwid#188]
I have a load screen created with a popup with an urwid progress bar in it. While this is loading (30s), while pressing a bunch of buttons and keys on my keyboard and mouse including ESC, then urwid consistently crashes with the following stack trace:

```
Traceback (most recent call last):
  File "./hicta", line 880, in <module>
    w = HardwareInventoryServiceTerminalClientApp()
  File "./hicta", line 102, in __init__
    self.loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/raw_display.py", line 466, in parse_input
    codes, wait_for_more)
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/escape.py", line 384, in process_keyqueue
    more_available)
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.1-py2.7-macosx-10.10-x86_64.egg/urwid/escape.py", line 385, in process_keyqueue
    if run[0] == "esc" or run[0].find("meta ") >= 0:
AttributeError: 'tuple' object has no attribute 'find'
```

When this crashes, this is the contents of run: `<type 'tuple'>: ('mouse press', 1, 104, 17)`

Maybe mouse events should be discarded or something like that instead?

**Comment by and3rson** [comment]
Fixed in #304.
