### ISSUE TITLE
Code from git seems to be broken on 3.5

### ISSUE THREAD

**Issue by magniff** [urwid/urwid#206]
using ubuntu 16
$ python3 -m venv venv
$ . venv/bin/activate

``` bash
$ python -c "import urwid"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/magniff/workspace/urwid/urwid/__init__.py", line 36, in <module>
    from urwid.wimp import (SelectableIcon, CheckBoxError, CheckBox, RadioButton,
  File "/home/magniff/workspace/urwid/urwid/wimp.py", line 99, in <module>
    class CheckBox(WidgetWrap):
  File "/home/magniff/workspace/urwid/urwid/wimp.py", line 104, in CheckBox
    True: SelectableIcon("[X]"),
  File "/home/magniff/workspace/urwid/urwid/wimp.py", line 47, in __init__
    self.__super.__init__(text)
AttributeError: 'SelectableIcon' object has no attribute '_SelectableIcon__super'

```

$ python --version
Python 3.5.2

**Comment by wardi** [comment]
you need to install urwid using setuptools and 2to3.

**Comment by magniff** [comment]
@wardi I beg a pardon, what?) There is a commit, namely https://github.com/urwid/urwid/commit/60741af8cbb8ff11b2cc6d09c6e5fdf0ff9d7b72
And it explicitly claims that py3.5 is now supported out of the box.

**Comment by wardi** [comment]
Yes, you should be able to install urwid e.g. with `python setup.py install` if you cloned this repo, or with `pip install urwid`.
