### ISSUE TITLE
Python 2: Resize test failures because of OSError: Interrupted system call

### ISSUE THREAD

**Issue by Apteryks** [urwid/urwid#230]
When attempting to run the tests for urwid 1.3.1 with Python 2.7.13 on GuixSD, I get the following failures:
````
test_run (urwid.tests.test_event_loops.SelectEventLoopTest) ... ok

======================================================================
FAIL: test_horizontal_resize (urwid.tests.test_vterm.TermTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test_vterm.py", line 175, in test_horizontal_resize
    self.expect('1-' + '\n' * 22 + '3-')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'1-\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n3-'
Got:
'\n\n\n\n\n\n\n\n\n\n\n\n\n\n3-\nTraceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/vterm.py",\n line 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test\n_vterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'

======================================================================
FAIL: test_vertical_resize (urwid.tests.test_vterm.TermTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test_vterm.py", line 186, in test_vertical_resize
    self.expect('\n' * (y - 2) + '3-' + ' ' * 76 + '-4', desc)
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: try to rescale to 80x22.
Expected:
'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n3-                                                                            -4'
Got:
'\n\n\n\n\n\n\n\n\n\n\n3-                                                                            -4\n\nTraceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-0/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'

----------------------------------------------------------------------
Ran 278 tests in 1.032s

FAILED (failures=2)
phase `check' failed after 5.6 seconds
builder for `/gnu/store/px05rmxgqr62z1jjyffsrp2l46gmm0x2-python2-urwid-1.3.1.drv' failed with exit code 1
cannot build derivation `/gnu/store/5hd9ypj93nqs94433vq6jmkrc3x1bq8w-wicd-1.7.4.drv': 1 dependencies couldn't be built
guix system: error: build failed: build of `/gnu/store/5hd9ypj93nqs94433vq6jmkrc3x1bq8w-wicd-1.7.4.drv' failed
````

It's currently reproducible on my system. I'm using GuixSD (git from master), with kernel Linux 4.10.3 x86_64.

If I use Python 3.5.2, I cannot reproduce the problem and all the tests pass.

**Comment by Apteryks** [comment]
Interestingly, if I rerun the tests with strace, the number of failures go up apparently randomly (I ran it a couple times, once with 8 failures, another time with 26 and 2 errors). Here's an excerpt of the strace output:

````
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_scrolling_region_reve"..., 69FAIL: test_scrolling_region_reverse (urwid.tests.test_vterm.TermTest)) = 69
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 764Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 220, in test_scrolling_region_reverse
    self.expect('\n\nbbb\nXXX\n\naaa')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'\n\nbbb\nXXX\n\naaa'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 764
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_scrolling_region_simp"..., 68FAIL: test_scrolling_region_simple (urwid.tests.test_vterm.TermTest)) = 68
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 831Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 216, in test_scrolling_region_simple
    self.expect('aa' + '\n' * 9 + '2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'aa\n\n\n\n\n\n\n\n\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 831
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_scrolling_twice (urwi"..., 60FAIL: test_scrolling_twice (urwid.tests.test_vterm.TermTest)) = 60
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 729Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 228, in test_scrolling_twice
    self.expect('\ntest')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'\ntest'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 729
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_set_leds (urwid.tests"..., 53FAIL: test_set_leds (urwid.tests.test_vterm.TermTest)) = 53
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 720Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 329, in test_set_leds
    self.expect('test1')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'test1'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 720
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_set_multiple_modes (u"..., 63FAIL: test_set_multiple_modes (urwid.tests.test_vterm.TermTest)) = 63
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 728Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 240, in test_set_multiple_modes
    self.expect('test')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'test'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 728
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_set_title (urwid.test"..., 54FAIL: test_set_title (urwid.tests.test_vterm.TermTest)) = 54
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 721Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 319, in test_set_title
    self.expect('test1')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'test1'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 721
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_simplestring (urwid.t"..., 57FAIL: test_simplestring (urwid.tests.test_vterm.TermTest)) = 57
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 736Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 124, in test_simplestring
    self.expect('hello world')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'hello world'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 736
write(2, "\n", 1
)                       = 1
write(2, "================================"..., 70======================================================================) = 70
write(2, "\n", 1
)                       = 1
write(2, "FAIL: test_wrap_simple (urwid.te"..., 56FAIL: test_wrap_simple (urwid.tests.test_vterm.TermTest)) = 56
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Traceback (most recent call last"..., 830Traceback (most recent call last):
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 250, in test_wrap_simple
    self.expect(' ' * (self.term.width - 1) + 't\nt')
  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_vterm.py", line 120, in expect
    self.assertEqual(got, what, desc)
AssertionError: Expected:
'                                                                               t\nt'
Got:
'Traceback (most recent call last):\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/vterm.py", l\nine 1389, in spawn\n    self.command()\n  File "/tmp/guix-build-python2-urwid-1.3.1.drv-1/urwid-1.3.1/urwid/tests/test_v\nterm.py", line 44, in __call__\n    data = os.read(self.reader, 1024)\nOSError: [Errno 4] Interrupted system call'
) = 830
write(2, "\n", 1
)                       = 1
write(2, "--------------------------------"..., 70----------------------------------------------------------------------) = 70
write(2, "\n", 1
)                       = 1
write(2, "Ran 278 tests in 4.319s", 23Ran 278 tests in 4.319s) = 23
write(2, "\n", 1
)                       = 1
write(2, "\n", 1
)                       = 1
write(2, "FAILED", 6FAILED)                   = 6
write(2, " (failures=26, errors=2)", 24 (failures=26, errors=2)) = 24
write(2, "\n", 1
)                       = 1
````
