### ISSUE TITLE
NameError: name 'fcntl' is not defined Windows 10 python 3.6

### ISSUE THREAD

**Issue by pyeguy** [urwid/urwid#240]
Using Xonsh + Exofrills editor (xo) which has `urwid` dependency

Getting the following traceback:

```python
$ xo .xonshrc
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\cpye\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 13343, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec)
  File "C:\Users\cpye\Anaconda3\lib\site-packages\xonsh\__amalgam__.py", line 12885, in proxy_two
    return f(args, stdin)
  File "C:\Users\cpye\Anaconda3\lib\site-packages\xontrib\xo.py", line 8, in _xo
    _main(args=args)
  File "C:\Users\cpye\Anaconda3\lib\site-packages\xo.py", line 1005, in main
    main_display.main(line, col)
  File "C:\Users\cpye\Anaconda3\lib\site-packages\xo.py", line 756, in main
    unhandled_input=self.unhandled_keypress)
  File "C:\Users\cpye\Anaconda3\lib\site-packages\urwid\main_loop.py", line 111, in __init__
    screen = raw_display.Screen()
  File "C:\Users\cpye\Anaconda3\lib\site-packages\urwid\raw_display.py", line 89, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
```

**Comment by LoganDark** [comment]
`fcntl` does not exist on Windows IIRC

**Comment by arkag** [comment]
Are there plans to remedy this? I'm interested in trying exofrills out but am unable to use it in my current environment...

**Comment by NikitaBeloglazov** [comment]
_*bump*_
Hey, is there any solution to this problem?
Issue remains on Python 3.11.5 and Windows 10 LTSC
Urwid 2.2.2

**Comment by penguinolog** [comment]
PR for windows support need to be rebased and fixed.

Op za 30 sep. 2023 14:43 schreef Nikita Beloglazov ***@***.***
