### ISSUE TITLE
Zero division error in graphics.py

### ISSUE THREAD

**Issue by SenchoPens** [urwid/urwid#254]
Whenever I start `sudo s-tui` I get the following traceback:

Traceback (most recent call last):
  File "/usr/bin/s-tui", line 11, in <module>
    load_entry_point('s-tui==0.5.0', 'console_scripts', 's-tui')()
  File "/usr/lib/python2.7/site-packages/s_tui/s_tui.py", line 768, in main
    graph_controller.main()
  File "/usr/lib/python2.7/site-packages/s_tui/s_tui.py", line 640, in main
    self.loop.run()
  File "/usr/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  ... (Lots of cached_render stuff here) ...
  File "/usr/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python2.7/site-packages/urwid/graphics.py", line 547, in render
    disp = self.calculate_display((maxcol, maxrow))
  File "/usr/lib/python2.7/site-packages/urwid/graphics.py", line 390, in calculate_display
    maxrow)
  File "/usr/lib/python2.7/site-packages/urwid/graphics.py", line 633, in calculate_bargraph_display
    segments = scale_bar_values(bar, top, maxrow)
  File "/usr/lib/python2.7/site-packages/urwid/graphics.py", line 794, in scale_bar_values
    return [maxrow - int(float(v) * maxrow / top + 0.5) for v in bar]
ZeroDivisionError: float division by zero

My urwid version is 1.3.1, terminal is termite v12.

**Comment by tonycpsu** [comment]
Seems to be caused by upstream program, see https://github.com/amanusk/s-tui/issues/28
