### ISSUE TITLE
terminal.py example throws error

### ISSUE THREAD

**Issue by harsh-98** [urwid/urwid#297]
##### Description:
on executing terminal.py it fails with error

>Traceback (most recent call last):                                                                          
  File "terminal.py", line 13, in <module>                                                                  
    loop.run()                                                                                               
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run              
    self._run()                                                                                              
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 375, in _run             
    self.event_loop.run()                                                                                    
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 678, in run              
    self._loop()                                                                                             
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 706, in _loop            
    self._entering_idle()                                                                                    
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 667, in _entering_idle   
    callback()                                                                                               
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 560, in entering_idle    
    self.draw_screen()                                                                                       
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/main_loop.py", line 575, in draw_screen      
    self.screen.draw_screen(self.screen_size, canvas)                                                       
  File "/home/harsh/anaconda3/lib/python3.6/site-packages/urwid/raw_display.py", line 837, in draw_screen    
    l = l.decode('utf-8')                                                                                    
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: unexpected end of data

**Comment by penguinolog** [comment]
Can you recheck with actual master branch? I can not reproduce issue.

**Comment by penguinolog** [comment]
Closing as not reproduced
