### ISSUE TITLE
Travis CI job for Python 3.3 fails: "RuntimeError: Python 3.4 or later is required"

### ISSUE THREAD

**Issue by olleolleolle** [urwid/urwid#320]
##### Description:

Travis CI fails the Python 3.3 build job before it even starts to run any tests.

##### Affected versions (if applicable)
- [x] `master` branch (specify commit) d020195b6a25166be1ba9c06939e872b1ab3f346
- [ ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

Run tests in 3.3: https://travis-ci.org/urwid/urwid/jobs/457813403

```
$ tox
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.6/bin/tox", line 7, in <module>
    from tox import cmdline
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tox/__init__.py", line 32, in <module>
    from .session import cmdline  # noqa
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/tox/session.py", line 18, in <module>
    import pkg_resources
  File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
The command "tox" exited with 1.
```

##### Expected/actual outcome

I expected all the Travis CI configured jobs to be able to run tests.

**Comment by tonycpsu** [comment]
Appears to be fixed by https://github.com/urwid/urwid/commit/1a3f7e12ebdb05b6738a241c35ad5aecab479d07
