### ISSUE TITLE
AssertionError: (0, 0, 0) in text_layout.py

### ISSUE THREAD

**Issue by josch** [urwid/urwid#342]
Hi,

i'm using urwid 2.0.1 from Debian unstable. When I resize alot to a certain window width I'm getting the following backtrace:

```
Traceback (most recent call last):
  File "/usr/bin/alot", line 11, in <module>
    load_entry_point('alot==0.8.1', 'console_scripts', 'alot')()
  File "/usr/share/alot/alot/__main__.py", line 137, in main
    UI(dbman, cmdstring)
  File "/usr/share/alot/alot/ui.py", line 141, in __init__
    self.mainloop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1340, in run
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1354, in wrapper
    rval = f(*args,**kargs)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1313, in _twisted_idle_callback
    callback()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 572, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/share/alot/alot/buffers/buffer.py", line 19, in render
    return self.body.render(size, focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/listbox.py", line 501, in render
    canvas = widget.render((maxcol,))
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/share/alot/alot/widgets/search.py", line 71, in render
    return urwid.AttrMap.render(self, size, focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 2087, in render
    focus = focus and self.focus_position == i)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 226, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 1004, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/lib/python3/dist-packages/urwid/canvas.py", line 1290, in apply_text_layout
    s = LayoutSegment(seg)
  File "/usr/lib/python3/dist-packages/urwid/text_layout.py", line 269, in __init__
    assert self.sc > 0, repr(seg)
AssertionError: (0, 0, 0)
```

I don't know how to make this problem reproducible for you because it totally depends on the selection of emails I have open.

**Comment by tonycpsu** [comment]
Yeah, that's a tough one.  You didn't mention the program, but the stack trace suggests it's `alot`.  If I were to install `alot`, is there anything in particular I can do to try to tickle this bug?

**Comment by josch** [comment]
Okay, I thought I wouldn't find out how to reproduce this but I did! \o/

Yes, this is with alot 0.8.1 from Debian unstable. The problem is triggered by exactly one email in the results. Luckily it's a spam email, so I don't care about violating the author's copyright or identity by pasting it here (modified a little bit to make it shorter):

```
Return-Path: <jangdy0218@chaveslopriatekelts.club>
List-Id: <jangdy0218.chaveslopriatekelts.club>
List-Unsubscribe:
 <mailto:jangdy0218@chaveslopriatekelts.club?subject=Unsubscribe>
From: =?utf-8?B?7J6l64uk7JyoIOyekeqwgA==?=
 <jangdy0218@chaveslopriatekelts.club>
Subject:
 =?utf-8?B?7J2066+47KeAIOyggOyekeq2jOychOuwmOycvOuhnCDsnbTrqZTsnbzrk5zr?=
 =?utf-8?B?pr3ri4jri6Qo7KCc7J6R7J6QIOuzuOyduCk=?=
To: josch@debian.org
Content-Type: multipart/mixed; charset=utf-8; boundary="ryq85M56fDxcOpFTW3rqD2r=_nkDUoksrg"
MIME-Version: 1.0
Date: Tue, 9 Apr 2019 03:21:31 -0700
Message-ID: <spamtest@spamtest5>

This is a multi-part message in MIME format

--ryq85M56fDxcOpFTW3rqD2r=_nkDUoksrg
Content-Type: multipart/alternative;
	boundary="R8VOI1XS1eVga84iS0of=_jYqjmusZCVDW"

--R8VOI1XS1eVga84iS0of=_jYqjmusZCVDW
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

=EC=95=88=EB=85=95=ED=95=98=EC=84=B8=EC=9A=94

=EB=8B=A4=EB=A6=84=EC=9D=B4 =EC=95=84=EB=8B=88=EB=9D=BC =EC=A0=9C=EB=AA=
=A9=EC=97=90 =EB=A7=90=EC=94=80=EB=93=9C=EB=A6=B0=EA=B2=83=EC=B2=98=EB=
=9F=BC =EC=A0=9C=EA=B0=80 =EC=A0=9C=EC=9E=91=ED=95=9C =EC=9D=B4=EB=AF=B8=
=EC=A7=80=EB=93=A4=EC=9D=80

=EB=AC=B4=EB=A3=8C=EB=A1=9C =EB=B0=B0=ED=8F=AC=EB=90=98=EA=B3=A0 =EC=9E=
=88=EB=8A=94 =EA=B7=B8=EB=A6=BC=EB=93=A4=EC=9D=B4 =EC=95=84=EB=8B=99=EB=
=8B=88=EB=8B=A4.

=EA=B7=B8=EB=A0=87=EA=B8=B0=EC=97=90 =EA=B7=B8=EB=83=A5 =EC=9D=B4=EC=9A=
=A9=ED=95=98=EC=8B=9C=EB=A9=B4 =EC=A0=80=EC=9E=91=EA=B6=8C=EB=B2=95=EC=
=83=81 =EB=AC=B8=EC=A0=9C=EA=B0=80 =EB=90=98=EC=84=B8=EC=9A=94..

=EC=86=94=EC=A7=81=ED=9E=88 =EB=B2=95=EC=A0=81=EC=9D=B8 =EC=9D=B4=EC=95=
=BC=EA=B8=B0=EB=A5=BC =ED=95=98=EB=A0=A4=EA=B3=A0 =EB=A9=94=EC=9D=BC=EB=
=93=9C=EB=A6=B0=EA=B1=B4 =EC=95=84=EB=8B=99=EB=8B=88=EB=8B=A4.

=EC=A0=80 =EC=97=AD=EC=8B=9C=EB=8F=84 =EC=8B=A4=EC=88=98=EB=A1=9C =EB=8B=
=A4=EB=A5=B8 =EC=9E=91=EA=B0=80=EB=8B=98 =EC=9D=B4=EB=AF=B8=EC=A7=80=EB=
=A5=BC =EC=82=AC=EC=9A=A9=ED=96=88=EB=8D=98=EC=A0=81=EB=8F=84 =EC=9E=88=
=EC=9C=BC=EB=8B=88=EA=B9=8C=EC=9A=94.

=EB=8B=B9=EC=97=B0 =EB=AA=A8=EB=A5=B4=EC=8B=9C=EA=B3=A0 =EA=B7=B8=EB=A0=
=A4=EC=85=A8=EC=9D=84=EA=BA=BC=EB=9D=BC =EC=83=9D=EA=B0=81=ED=95=B4=EC=
=9A=94.

=EB=8B=A4=EB=A7=8C =EC=9D=B4=EC=A0=9C=EB=8A=94 =EA=B3=A0=EC=A7=80=ED=95=
=B4=EB=93=9C=EB=A0=B8=EC=9C=BC=EB=8B=88 =EC=A7=80=EA=B8=88=EB=B6=80=ED=
=84=B4 =EC=82=AC=EC=9A=A9=EC=9D=84 =EA=B8=88=ED=95=B4=EC=A3=BC=EC=84=B8=
=EC=9A=94.

=EC=9B=90=EB=B3=B8=EC=9D=B4=EB=AF=B8=EC=A7=80=EB=9E=91 =EC=82=AC=EC=9A=
=A9=ED=95=98=EC=8B=9C=EA=B3=A0 =EC=9E=88=EC=9C=BC=EC=8B=A0=EA=B1=B0 pd=
f=EB=A1=9C =EB=B3=B4=EB=82=B4=EB=93=9C=EB=A6=BD=EB=8B=88=EB=8B=A4.

=EC=A0=9C=EC=9E=91=EC=9E=90=EB=A1=9C =ED=99=9C=EB=8F=99=ED=95=98=EB=8B=
=A4=EB=B3=B4=EB=A9=B4 =EC=9D=B4=EB=9F=B0=EB=B6=80=EB=B6=84=EC=97=90=EC=
=84=9C =EC=95=A0=EB=A1=9C=EC=82=AC=ED=95=AD=EC=9D=B4 =EB=A7=8E=EC=8A=B5=
=EB=8B=88=EB=8B=A4.

=EB=A7=90=EC=94=80=EC=9D=84 =EB=93=9C=EB=A0=B8=EC=A7=80=EB=A7=8C =EB=8B=
=A4=EB=A5=B8 =EC=A1=B0=EC=B9=98=EB=A5=BC =EC=95=88=ED=95=B4=EC=A3=BC=EC=
=8B=9C=EB=A9=B4 =EA=B7=B8=EB=95=8C=EB=8A=94 =EC=A0=80=EB=8F=84 =EC=96=B4=
=EC=A9=94=EC=88=98=EC=97=86=EC=96=B4=EC=9A=94..=E3=85=9C=E3=85=9C

=EA=B7=B8=EB=9F=AC=EB=8B=88 =EA=BC=AD =ED=99=95=EC=9D=B8=ED=95=98=EC=8B=
=9C=EA=B3=A0 =EB=B9=A0=EB=A5=B8=EC=A1=B0=EC=B9=98 =EB=B6=80=ED=83=81=EB=
=93=9C=EB=A6=AC=EA=B2=A0=EC=8A=B5=EB=8B=88=EB=8B=A4.

=EA=B7=B8=EB=9F=BC =EC=88=98=EA=B3=A0=ED=95=98=EC=84=B8=EC=9A=94.

--R8VOI1XS1eVga84iS0of=_jYqjmusZCVDW
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<html>
  <body bgcolor=3D"#eaeaea">
    foo
  </body>
</html>

--R8VOI1XS1eVga84iS0of=_jYqjmusZCVDW--

--ryq85M56fDxcOpFTW3rqD2r=_nkDUoksrg
Content-Type: application/octet-stream;
	name="=?utf-8?B?7J2066+47KeAIOustOuLqOyCrOyaqSDrgrTsmqkuYWx6?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="=?utf-8?B?7J2066+47KeAIOustOuLqOyCrOyaqSDrgrTsmqkuYWx6?="

foo
```
