### ISSUE TITLE
remove_watch_pipe with TrioEventLoop leads to EBADF

### ISSUE THREAD

**Issue by mwhudson** [urwid/urwid#378]
##### Description:
It seems that loop.remove_watch_pipe() with the new TrioEventLoop does not fully remove the pip from the event loop, leading to trio trying to call epoll_add on a closed fd.

##### Affected versions (if applicable)
- [x] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

This is with tip trio, although it fails in a very similar way with 0.13.0:

```
(master *)mwhudson@anduril:~/src/upstream/urwid$ cat ~/tmp/t.py
import urwid
import os

def cb(x):
    loop.remove_watch_pipe(p)
    txt.set_text("received {}".format(repr(x)))

def show_or_exit(key):
    if key in ('q', 'Q'):
        raise urwid.ExitMainLoop()
    os.write(p, b'x')

txt = urwid.Text(u"Hello World")
fill = urwid.Filler(txt, 'top')
loop = urwid.MainLoop(fill, unhandled_input=show_or_exit, event_loop=urwid.TrioEventLoop())
p = loop.watch_pipe(cb)
loop.run()
(master *)mwhudson@anduril:~/src/upstream/urwid$ ~/src/venv/bin/python3 ~/tmp/t.py
/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  category=RuntimeWarning
[ press a key ]
Traceback (most recent call last):
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_epoll.py", line 235, in _update_registrations
    self._epoll.modify(fd, wanted_flags | select.EPOLLONESHOT)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwhudson/tmp/t.py", line 17, in <module>
    loop.run()
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/urwid/_async_kw_event_loop.py", line 143, in run
    self._trio.run(self._main_task, instruments=[emulate_idle_callbacks])
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/urwid/_async_kw_event_loop.py", line 189, in _main_task
    await self._trio.sleep_forever()
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/urwid/_async_kw_event_loop.py", line 231, in _watch_task
    await self._wait_readable(fd)
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_generated_io_epoll.py", line 12, in wait_readable
    return await GLOBAL_RUN_CONTEXT.runner.io_manager.wait_readable(fd)
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_epoll.py", line 275, in wait_readable
    await self._epoll_wait(fd, "read_task")
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_epoll.py", line 264, in _epoll_wait
    self._update_registrations(fd)
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_epoll.py", line 250, in _update_registrations
    wake_all(waiters, exc)
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_common.py", line 22, in wake_all
    raise exc
  File "/home/mwhudson/src/venv/lib/python3.7/site-packages/trio/_core/_io_epoll.py", line 239, in _update_registrations
    fd, wanted_flags | select.EPOLLONESHOT
OSError: [Errno 9] Bad file descriptor
```

##### Expected/actual outcome

Well, it not crashing. I can make this go away with this simple diff:

```
(master *)mwhudson@anduril:~/src/upstream/urwid$ git diff
diff --git a/urwid/_async_kw_event_loop.py b/urwid/_async_kw_event_loop.py
index cc7728f..5630b61 100644
--- a/urwid/_async_kw_event_loop.py
+++ b/urwid/_async_kw_event_loop.py
@@ -230,3 +230,5 @@ class TrioEventLoop(EventLoop):
             while True:
                 await self._wait_readable(fd)
                 callback()
+                if scope.cancel_called:
+                    return
```

But I hardly know if this is appropriate.

**Comment by mwhudson** [comment]
Ah so the crash is caused by remove_watch_pipe being called inside the callback. If you 'defer' the call to remove_watch_pipe to another event loop iteration with loop.set_alarm_in(0.0, ...) it all works. I think this makes my patch look slightly more reasonable...

**Comment by mwhudson** [comment]
Or is this a trio bug that trio.hazmat.wait_readable does not check for a cancelled scope?

**Comment by njsmith** [comment]
I think your patch looks reasonable, except that you should probably move the check directly before the `wait_readable` call (or make it `while not scope.cancel_called`). This also fixes the unlikely-but-theoretically-possible case where a watch handle is removed *immediately* after being registered, before the first iteration of the loop.

And add a comment explaining why this is needed :-)
