### ISSUE TITLE
Crash on `fg`, SIGCONT (after Ctrl-Z, SIGSTOP, SIGTSTP)

### ISSUE THREAD

**Issue by goncalopp** [urwid/urwid#400]
##### Description:
`urwid` crashes after resuming any process with `fg` after `ctrl-z`

##### Affected versions (if applicable)

- [x] `master` branch (9c70860b79ea9e68a1b188d14c3c89ff161718d3)
- [x] Latest stable version from `pypi`

##### Steps to reproduce (if applicable)

 - Run the tutorial application
 - Ctrl-Z
 - `fg`

##### Expected/actual outcome

Outcome:

```
Traceback (most recent call last):
  File "bug.py", line 15, in <module>
    loop.run()
  File "/home/goncalopp/urwid/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/goncalopp/urwid/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/goncalopp/urwid/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/goncalopp/urwid/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
KeyError: 4
```

##### Fix

After some debugging, I found the problem. PR will follow shortly

**Comment by goncalopp** [comment]
Unrelated bug, but same topic - #25
