### ISSUE TITLE
When I try installation  with pip urwid I'm get TypeError: pip install urwid

### ISSUE THREAD

**Issue by sysuls1** [urwid/urwid#402]
##### Description:
    running build_ext
    building 'urwid.str_util' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-fwue2j4a\urwid\setup.py", line 83, in <module>
        setup(**setup_d)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
        _build_ext.run(self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "C:\ProgramData\Anaconda3\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
        if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
      File "C:\ProgramData\Anaconda3\lib\genericpath.py", line 30, in isfile
        st = os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-fwue2j4a\\urwid\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-fwue2j4a\\urwid\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-t1qo4q4q\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\urwid' Check the logs for full command output.

python3.7.6

**Comment by tonycpsu** [comment]
Looks like you're trying to install in Windows.  Urwid can be installed on Windows, but only via [Cygwin](http://www.cygwin.com/).

**Comment by ulidtko** [comment]
I'm actually very keen to drop that `str_util.c` altogether, it seems totally out of place. It is optional anyway (e.g. unused on PyPy). Having urwid as a *pure-python* library IMO would outweigh a minuscule performance benefit (if it actually exists and matters) from that C extension.

But it remains to be measured.

----------
@sysuls1 you may be able to build with native (non-cygwin) python by:
 1. configuring setuptools with your C compiler (msvc) properly; or
 2. commenting out the line with `ext_modules` in urwid's setup.py.

**Comment by penguinolog** [comment]
The next release of `urwid` will provide limited Windows support and should be published pre-compiled for Windows.

**Comment by penguinolog** [comment]
Version 2.4.0 with basic windows support just released.
