### ISSUE TITLE
BigText widget causes error when used in menu

### ISSUE THREAD

**Issue by MonAaraj** [urwid/urwid#413]
##### Description:
using BigText inside an array with Dividers and a few buttons within a Padding and trying to view them inside an overlay causes an exception:
```py3-traceback
Traceback (most recent call last):
  File "DatInkTank1.py", line 42, in <module>
    loop.run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 818, in _loop
    self._entering_idle()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 779, in _entering_idle
    callback()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 574, in entering_idle
    self.draw_screen()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 588, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.8/site-packages/urwid/container.py", line 782, in render
    top_c = self.top_w.render(
  File "/usr/local/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.8/site-packages/urwid/decoration.py", line 567, in render
    canv = self._original_widget.render((maxcol,)+size[1:], focus)
  File "/usr/local/lib/python3.8/site-packages/urwid/widget.py", line 145, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 426, in render
    middle, top, bottom = self.calculate_visible(
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 309, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 673, in _set_focus_complete
    return self._set_focus_first_selectable(
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 643, in _set_focus_first_selectable
    middle, top, bottom = self.calculate_visible(
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 376, in calculate_visible
    n_rows = next.rows( (maxcol,) )
```

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
use this code:
```python3
import urwid

def exit_on_key(key):
   if key == 'esc':
        raise urwid.ExitMainLoop()

def start_menu(title):
    body = [urwid.Divider(), urwid.BigText(('bold', title), None), urwid.Divider(), urwid.Divider()]

    buttons = [
        urwid.Button(u"Play", on_press=start_game),
        urwid.Button(u"Credits", on_press=play_credits),
        urwid.Button(u"Quit", on_press=exit_program)
    ]

    for btn in buttons:
        body.append(urwid.AttrMap(btn, None, focus_map='reversed'))

    return urwid.ListBox(urwid.SimpleFocusListWalker(body))

def exit_program(button):
    raise urwid.ExitMainLoop()

def play_credits(button):
    pass

def start_game(button):
    pass


main = urwid.Padding(start_menu("DatInk\nTank"), left=4, right=4)

top = urwid.Overlay(main, urwid.SolidFill(u'\N{MEDIUM SHADE}'),
    align='center', width=('relative', 60),
    valign='middle', height=('relative', 60),
    min_width=20, min_height=9, top=3)


loop = urwid.MainLoop(top, palette=[('reversed', 'light magenta,standout', 'white'), (None, '', 'dark magenta')], unhandled_input=exit_on_key)

loop.screen.set_terminal_properties(colors=256)
loop.run()
```

##### Expected/actual outcome
To be displayable inside the padding and overlay without exceptions

**Comment by tonycpsu** [comment]
Two problems:

1.  You have to supply a `Font` for `BigText` – `None` won't do.  Generally, if there's a positional argument, it means "you need to supply a value for this".  Sometimes things will default to `None` with keyword arguments, in which case it's safe to assume a value isn't necessary.

2.  `BigText` [is a `Fixed` widget](http://urwid.org/manual/widgets.html#box-flow-and-fixed-widgets).  The easiest way to deal with it in this case is to wrap it in a `Padding` with `width=clip`, e.g.:

```python
    body = [urwid.Divider(),
            urwid.Padding(urwid.BigText(
                ('bold', title), urwid.HalfBlock5x4Font()
            ), width="clip"),
            urwid.Divider(), urwid.Divider()]
```

**Comment by MonAaraj** [comment]
Next it just shows `?` marks in the place it was supposed to be in

**Comment by tonycpsu** [comment]
That looks like an encoding issue with your terminal.  The characters used in the fonts are high ASCII block drawing characters, which sometimes don't render if there's a mismatch.

**Comment by MonAaraj** [comment]
I see, thank you!
