### ISSUE TITLE
test_locale test assumes en_US.UTF8 locale is available

### ISSUE THREAD

**Issue by light** [urwid/urwid#436]
```
ERROR: test_locale (urwid.tests.test_util.PortabilityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vic/.cache/yay/python2-urwid/src/urwid-release-2.1.1/urwid/tests/test_util.py", line 207, in test_locale
    locale.setlocale(locale.LC_ALL, ('en_US', 'UTF-8'))
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting
```

Present in 2.1.1 and in master branch.

The `en_US.UTF8` locale was not installed on the system where this error occurred. After installing that locale, the error went away.

**Comment by penguinolog** [comment]
Reproduced in docker container
