### ISSUE TITLE
Please release a new version that includes #415 (locale fix) 

### ISSUE THREAD

**Issue by ulope** [urwid/urwid#437]
##### Description:
#415 fixed an issue that would cause importing urwid to raise a locale error on some systems.
Unfortunately there has so far been no release that includes this fix.
This makes using urwid unnecessarily complicated inside many docker containers (and thereby also on many CI systems) since those often ship with only the `C.UTF-8` locale.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
```
docker run --rm -it ubuntu:20.04 /bin/bash -c 'apt update; apt install -y python3-pip; python3 -m pip install urwid; python3 -c "import urwid; print(True)"'
```

##### Expected/actual outcome
- Expected: 
  `True` to be printed.
- Actual:
  ```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.8/dist-packages/urwid/__init__.py", line 26, in <module>
      from urwid.widget import (FLOW, BOX, FIXED, LEFT, RIGHT, CENTER, TOP, MIDDLE,
    File "/usr/local/lib/python3.8/dist-packages/urwid/widget.py", line 27, in <module>
      from urwid.util import (MetaSuper, decompose_tagmarkup, calc_width,
    File "/usr/local/lib/python3.8/dist-packages/urwid/util.py", line 61, in <module>
      detected_encoding = detect_encoding()
    File "/usr/local/lib/python3.8/dist-packages/urwid/util.py", line 58, in detect_encoding
      locale.setlocale(locale.LC_ALL, initial)
    File "/usr/lib/python3.8/locale.py", line 608, in setlocale
      return _setlocale(category, locale)
  locale.Error: unsupported locale setting
  ```

**Comment by tonycpsu** [comment]
Done.
```
Collecting urwid
  Downloading urwid-2.1.2.tar.gz (634 kB)
     |████████████████████████████████| 634 kB 1.8 MB/s
Building wheels for collected packages: urwid
  Building wheel for urwid (setup.py) ... done
  Created wheel for urwid: filename=urwid-2.1.2-cp38-cp38-linux_x86_64.whl size=259099 sha256=73bab165de5c8d96eb3fd0eb869bd352cccabb63f813c3d3cf6f9203c3e1634e
  Stored in directory: /root/.cache/pip/wheels/28/71/e4/38b5d81438105d0e3db5016cf2eea6fa796d89d96a04451d4d
Successfully built urwid
Installing collected packages: urwid
Successfully installed urwid-2.1.2
True
```

**Comment by ulope** [comment]
Awesome, thanks!
