### ISSUE TITLE
ListBoxError: Invalid offset_inset: -30, only 4 rows in target, with pile of buttons twice wider than the screen.

### ISSUE THREAD

**Issue by Carreau** [urwid/urwid#467]
##### Description:

With some weird combinaisons of widgets and pressing pagedown as the first keypress, I can get urwid to crash.

##### Affected versions (if applicable)
- [x] `master` branch (release-2.1.2-11-gc93aeb2, c93aeb23fbca0ce8f12187ebc3ca330443a3bf6b)
- [x] Latest stable version from `pypi`, (git checkout release-2.1.2, 82199baecb8545a9503fe24ade5d9360f167ba8c)
- [x] Other (specify source), 2.0.0 at leat (tried to git-bisect, and gave up when it was not Python 3 compatible anymore, so old bug).

##### Steps to reproduce (if applicable)

Run following snippet in terminal (for example 83x31), and press pagedown (fn-down-arrow on mac os), before pressing anything else. 

```python
import urwid
import urwid.raw_display


def main(*args, **kwargs):

    seq = [
        urwid.Divider(),
        urwid.Pile([urwid.Text("W"), urwid.Text("W" * 194)]),
        urwid.Pile([urwid.Button("X" * 160) for i in range(20)]),
    ]

    listbox = urwid.ListBox(seq)
    frame = urwid.Frame(listbox)

    screen = urwid.raw_display.Screen()

    def unhandled(key):
        if key == "q":
            raise urwid.ExitMainLoop()

    urwid.MainLoop(frame, None, screen, unhandled_input=unhandled).run()


if "__main__" == __name__:
    main()
```

This results in 

```
$ python fail.py
Traceback (most recent call last):
  File "fail.py", line 26, in <module>
    main()
  File "fail.py", line 22, in main
    urwid.MainLoop(frame, None, screen, unhandled_input=unhandled).run()
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 287, in run
    self._run()
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/Users/bussonniermatthias/dev/urwid/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/Users/bussonniermatthias/dev/urwid/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/Users/bussonniermatthias/dev/urwid/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/Users/bussonniermatthias/dev/urwid/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/Users/bussonniermatthias/dev/urwid/urwid/listbox.py", line 988, in keypress
    return actual_key(self._keypress_page_down((maxcol, maxrow)))
  File "/Users/bussonniermatthias/dev/urwid/urwid/listbox.py", line 1497, in _keypress_page_down
    self.change_focus( (maxcol,maxrow), pos,
  File "/Users/bussonniermatthias/dev/urwid/urwid/listbox.py", line 862, in change_focus
    raise ListBoxError("Invalid offset_inset: %s, only %s rows in target!" %(offset_inset, tgt_rows))
urwid.listbox.ListBoxError: Invalid offset_inset: -30, only 4 rows in target!
```

Note that this appear to happen only if the terminal is narrow enough so that buttons text wraps **twice**, and there need to be enough buttons that the pagedown has something to scroll.

I was not able to reduce more the first pile, it seem necessary for the focus not not be on the pile of button and trigger the crash. The divider is also necessary.

This is not limited to buttons, it was originally triggered with a custom TextRendered of mine, but is "easy" to reproduce with buttons. Once one of the button had had focus the bug will not reproduce anymore.

##### Expected/actual outcome

Don't crash. Scroll to somewhere in the listbox.

---- 

Note:

Don't try to debug with `[urwid.Button("X" * 160)]*20`, like me for an hour, urwid don't like to have the same button instance in multiple places...

I haven't dug too far in this; I'm not even sure what offset_inset is and if negative values are fine. Still wrapping my head about the internal and relatively new to urwid; so maybe pebkac.

Thanks.

**Comment by Carreau** [comment]
Diggin into this, I can see the the keydown trigger two changes in focus, could the be the case?
```
~/dev/urwid/urwid/listbox.py:851|request to change focus to size=(135, 46), position=2, offset_inset=-42, coming_from='above', cursor_coords=('left', 87)
~/dev/urwid/urwid/listbox.py:851|request to change focus to size=(135, 46), position=1, offset_inset=-45, coming_from='above', cursor_coords=None
```

first one coming from

```
for i in search_order:
   ...
   else:
                self.change_focus(
                    (maxcol, maxrow),
                    pos,
                    row_offset,
                    "above",
                    (self.pref_col, pref_row),
                    snap_rows,
                )

```

Maybe the two changes in focus invalidate some changes in local variable, in particular:

```
row_offset, widget, pos, rows = t[i]
```

Where row_offset is used for the second change in focus; while `t` is computed before the first, so likely incorrect by then.

**Comment by penguinolog** [comment]
Can not reproduce.
Following chain of fixes in ListBox focus and sizing handling expect fixed.
Closing.
