### ISSUE TITLE
Importing urwid breaks strptime() because of locale

### ISSUE THREAD

**Issue by undera** [urwid/urwid#479]
##### Description:
Consider following snippet:
```
import datetime
import locale
import os

print("Lang: "+os.getenv("LANG"))
print("LC_ALL: "+os.getenv("LC_ALL", "None"))

try:
    print(locale.getlocale(locale.LC_ALL))
except BaseException as exc:
    print("First exception: %s" % exc)

from urwid import util

try:
    print(locale.getlocale(locale.LC_ALL))
except BaseException as exc:
    print("Second exception: %s" % exc)

val = 'Fri, 07 Aug 2020 18:15:28 GMT'
expires = datetime.datetime.strptime(val, "%a, %d %b %Y %H:%M:%S GMT")
print("worked")
```

I have following output:
```
# /usr/bin/python3.8 demo.py
Lang: ru_RU.UTF-8
LC_ALL: None
First exception: category LC_ALL is not supported
('ru_RU', 'UTF-8')
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    expires = datetime.datetime.strptime(val, "%a, %d %b %Y %H:%M:%S GMT")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'Fri, 07 Aug 2020 18:15:28 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
```

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Just run the provided snippet with corresponding locale setup

##### Expected/actual outcome
If I comment out import of urwid util, it starts to work as expected.

From my investigation, this happens because urwid sets locale back for LC_ALL, while it was not set beforehand. It reads from `initial = locale.getlocale()` with no LC_ALL, but then sets to LC_ALL with `locale.setlocale(locale.LC_ALL, initial)`, which creates global side effect.

**Comment by undera** [comment]
Output of my `locale`:
```
LANG=ru_RU.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=C
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

**Comment by elenril** [comment]
I'm encountering this as well, apparently it's caused by urwid's encoding detection messing with locales. Is there any reason urwid does not just call locale.getpreferredencoding()?
