### ISSUE TITLE
Pile default focus not handled well when contents is modified

### ISSUE THREAD

**Issue by vapier** [urwid/urwid#492]
to reproduce:
```python
import urwid
# Create a Pile with no focusable element.
pile = urwid.Pile([urwid.Divider('-')])
# Add a focusable element.
pile.contents.append((urwid.Edit(edit_text=''), ('weight', 1)))
# Send a keypress.
pile.keypress((1,), 'enter')
```

at this point it crashes
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
AttributeError: 'Divider' object has no attribute 'keypress'
```

if the focus is changed manually first via `pile.set_focus(1)`, then there is no crash.

what makes this annoying is that if all the elements were added during initialization, then the focusable element (Edit) would have been selected automatically instead.

should Pile handle default focus better ?  or should this be documented as WAI ?

**Comment by penguinolog** [comment]
Marking as feature request due to automatic focus recalculation is not implemented in several widgets by design
