### ISSUE TITLE
Can't Build HTML Documentation

### ISSUE THREAD

**Issue by BioBox** [urwid/urwid#509]
##### Description:
I can't build the html documentation for urwid.

```
Running Sphinx v4.5.0
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 29 source files that are out of date
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [  3%] changelog
reading sources... [  6%] examples/index
reading sources... [ 10%] index
reading sources... [ 13%] manual/canvascache
reading sources... [ 17%] manual/displayattributes
reading sources... [ 20%] manual/displaymodules
reading sources... [ 24%] manual/encodings
reading sources... [ 27%] manual/index
reading sources... [ 31%] manual/mainloop
reading sources... [ 34%] manual/overview
reading sources... [ 37%] manual/textlayout
reading sources... [ 41%] manual/userinput
reading sources... [ 44%] manual/widgets
reading sources... [ 48%] reference/attrspec
reading sources... [ 51%] reference/canvas
reading sources... [ 55%] reference/command_map
reading sources... [ 58%] reference/constants
reading sources... [ 62%] reference/deprecated
reading sources... [ 65%] reference/display_modules
reading sources... [ 68%] reference/exceptions
reading sources... [ 72%] reference/global_settings
reading sources... [ 75%] reference/index
reading sources... [ 79%] reference/list_walkers
reading sources... [ 82%] reference/main_loop
reading sources... [ 86%] reference/meta
reading sources... [ 89%] reference/signals
reading sources... [ 93%] reference/text_layout
reading sources... [ 96%] reference/widget
reading sources... [100%] tutorial/index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  3%] changelog
writing output... [  6%] examples/index
writing output... [ 10%] index
writing output... [ 13%] manual/canvascache
writing output... [ 17%] manual/displayattributes
writing output... [ 20%] manual/displaymodules
writing output... [ 24%] manual/encodings
writing output... [ 27%] manual/index
writing output... [ 31%] manual/mainloop
writing output... [ 34%] manual/overview
writing output... [ 37%] manual/textlayout
writing output... [ 41%] manual/userinput
writing output... [ 44%] manual/widgets
writing output... [ 48%] reference/attrspec
writing output... [ 51%] reference/canvas
writing output... [ 55%] reference/command_map
writing output... [ 58%] reference/constants
writing output... [ 62%] reference/deprecated
writing output... [ 65%] reference/display_modules
writing output... [ 68%] reference/exceptions
writing output... [ 72%] reference/global_settings
writing output... [ 75%] reference/index
writing output... [ 79%] reference/list_walkers
writing output... [ 82%] reference/main_loop
writing output... [ 86%] reference/meta
writing output... [ 89%] reference/signals
writing output... [ 93%] reference/text_layout
writing output... [ 96%] reference/widget
writing output... [100%] tutorial/index

/usr/lib/python3.10/site-packages/urwid/decoration.py:docstring of urwid.decoration.WidgetDecoration.selectable:10: WARNING: more than one target found for cross-reference 'keypress': urwid.Widget.keypress, urwid.Edit.keypress, urwid.IntEdit.keypress, urwid.Button.keypress, urwid.CheckBox.keypress, urwid.TreeWidget.keypress, urwid.SelectableIcon.keypress, urwid.Padding.keypress, urwid.Filler.keypress, urwid.Frame.keypress, urwid.ListBox.keypress, urwid.TreeListBox.keypress, urwid.Columns.keypress, urwid.Pile.keypress, urwid.GridFlow.keypress, urwid.Overlay.keypress
/usr/lib/python3.10/site-packages/urwid/decoration.py:docstring of urwid.decoration.WidgetDisable.selectable:10: WARNING: more than one target found for cross-reference 'keypress': urwid.Widget.keypress, urwid.Edit.keypress, urwid.IntEdit.keypress, urwid.Button.keypress, urwid.CheckBox.keypress, urwid.TreeWidget.keypress, urwid.SelectableIcon.keypress, urwid.Padding.keypress, urwid.Filler.keypress, urwid.Frame.keypress, urwid.ListBox.keypress, urwid.TreeListBox.keypress, urwid.Columns.keypress, urwid.Pile.keypress, urwid.GridFlow.keypress, urwid.Overlay.keypress
generating indices... genindex done
writing additional pages... index failed

Traceback (most recent call last):
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1048, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/jinja2glue.py", line 188, in render
    return self.environment.get_template(template).render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/daniel/proj/urwid/docs/tools/templates/indexcontent.html", line 1, in top-level template code
    {% extends "!defindex.html" %}
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/themes/basic/defindex.html", line 9, in top-level template code
    #}{{ warn('Now base template defindex.html is deprecated.') }}
  File "/usr/lib/python3.10/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/usr/lib/python3.10/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'warn' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 353, in build
    self.finish()
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 637, in finish
    self.finish_tasks.add_task(self.gen_additional_pages)
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/util/parallel.py", line 34, in add_task
    res = task_func()
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/util/__init__.py", line 540, in wrapper
    return f(*args, **kwargs)
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 667, in gen_additional_pages
    self.handle_page(pagename, {}, template)
  File "/home/daniel/.local/python/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 1055, in handle_page
    raise ThemeError(__("An error happened in rendering the page %s.\nReason: %r") %
sphinx.errors.ThemeError: An error happened in rendering the page index.
Reason: UndefinedError("'warn' is undefined")

Theme error:
An error happened in rendering the page index.
Reason: UndefinedError("'warn' is undefined")
```
##### Affected versions (if applicable)
- [x] `master` branch (95C15)
- [ ] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
Go into `docs/` and run `sphinx-bulid -vb html . _build`.

##### Expected/actual outcome
Finish the documentation building without any errrors.

As a side note, I'd like to add that the build system under `docs/` is rather poor; the Makefile doesn't run sphinx, and it shouldn't rely on `uxrvt` or `xdotool`. Why it does this I do not know, but it should follow the example set by other python projects.

**Comment by ulidtko** [comment]
Hey @BioBox, thanks for reporting.

I can explain why the docs build uses `urxvt` and `xdotool`. It's a crude — though rather simple — automation for taking screenshots. Ian Wardi, the original author of Urwid, wrote it. The images you see on the [examples](http://urwid.org/examples/) & [tutorial](http://urwid.org/tutorial) pages — those are taken through a script; not manually.

This automation is "almost ready for CI", a GH Actions pipeline (or whatever) could run it — except for one issue :point_right:  #358. There's a subtle race condition; depending on the machine and its load, sometimes a screenshot will get taken too early. I've been having a really hard time with that issue. Welcome to check that branch of mine; it also has some cleanups and fixes in the examples.

Will appreciate concrete samples of how "other python projects" achieve the same (taking screenshots of how a program looks at docs-build-time). Nobody cared much of the docs before, so if you figure out how to update/repair the sphinx build and send a patch/PR — that'd be great as well.

**Comment by penguinolog** [comment]
Documentation is CI built for almost any PR + on release build
Screenshots build fixed in #1326
