### ISSUE TITLE
test failures with python-3.11

### ISSUE THREAD

**Issue by grozin** [urwid/urwid#511]
##### Description:
AttributeError: module 'asyncio' has no attribute 'coroutine'
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'

##### Affected versions (if applicable)
2.1.2

##### Steps to reproduce (if applicable)
python3.11 setup.py test
...
======================================================================
ERROR: test_coroutine_error (urwid.tests.test_event_loops.AsyncioEventLoopTest.test_coroutine_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/tests/test_event_loops.py", line 207, in test_coroutine_error
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

======================================================================
ERROR: test_event_loop (urwid.tests.test_event_loops.TornadoEventLoopTest.test_event_loop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/tests/test_event_loops.py", line 113, in setUp
    self.evl = urwid.TornadoEventLoop(IOLoop())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1102, in __init__
    self._patch_poll_impl(ioloop)
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1095, in _patch_poll_impl
    ioloop._impl = cls.PollProxy(ioloop._impl, idle_map)
                                 ^^^^^^^^^^^^
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'

======================================================================
ERROR: test_remove_alarm (urwid.tests.test_event_loops.TornadoEventLoopTest.test_remove_alarm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/tests/test_event_loops.py", line 113, in setUp
    self.evl = urwid.TornadoEventLoop(IOLoop())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1102, in __init__
    self._patch_poll_impl(ioloop)
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1095, in _patch_poll_impl
    ioloop._impl = cls.PollProxy(ioloop._impl, idle_map)
                                 ^^^^^^^^^^^^
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'

======================================================================
ERROR: test_remove_watch_file (urwid.tests.test_event_loops.TornadoEventLoopTest.test_remove_watch_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/tests/test_event_loops.py", line 113, in setUp
    self.evl = urwid.TornadoEventLoop(IOLoop())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1102, in __init__
    self._patch_poll_impl(ioloop)
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1095, in _patch_poll_impl
    ioloop._impl = cls.PollProxy(ioloop._impl, idle_map)
                                 ^^^^^^^^^^^^
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'

======================================================================
ERROR: test_run (urwid.tests.test_event_loops.TornadoEventLoopTest.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/tests/test_event_loops.py", line 113, in setUp
    self.evl = urwid.TornadoEventLoop(IOLoop())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1102, in __init__
    self._patch_poll_impl(ioloop)
  File "/home/grozin/tmp/urwid-2.1.2.orig/urwid/main_loop.py", line 1095, in _patch_poll_impl
    ioloop._impl = cls.PollProxy(ioloop._impl, idle_map)
                                 ^^^^^^^^^^^^
AttributeError: 'AsyncIOLoop' object has no attribute '_impl'

----------------------------------------------------------------------
Ran 325 tests in 2.429s

FAILED (errors=5)
Test failed: <unittest.runner.TextTestResult run=325 errors=5 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=325 errors=5 failures=0>

**Comment by penguinolog** [comment]
Finally fixed in master branch by #524

**Comment by dvzrv** [comment]
Can this please be released? That would be much appreciated! :)
We are currently trying to upgrade the Python ecosystem to 3.11 on Arch Linux.
