### ISSUE TITLE
Test failures in test_linefeed and test_scrolling_region_reverse_with_focus

### ISSUE THREAD

**Issue by wizeman** [urwid/urwid#514]
##### Description:

I've experienced test failures in `test_linefeed` and `test_scrolling_region_reverse_with_focus` when building urwid 2.1.2.

##### Affected versions (if applicable)
- [ ] `master` branch (specify commit)
- [X] Latest stable version from `pypi`
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)

I just built python3Packages.urwid with Nix, which I have been doing for a long time.

So I suspect this is a non-deterministic test failure.

##### Expected/actual outcome

I expected the tests to pass.

Instead, I got these failures:

```
======================================================================
FAIL: test_linefeed (urwid.tests.test_vterm.TermTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/urwid-2.1.2/urwid/tests/test_vterm.py", line 138, in test_linefeed
    self.expect('hello\nworld')
  File "/build/urwid-2.1.2/urwid/tests/test_vterm.py", line 130, in expect
    self.assertEqual(got, what, desc)
AssertionError: b'hello' != b'hello\nworld' : Expected:
b'hello\nworld'
Got:
b'hello'

======================================================================
FAIL: test_scrolling_region_reverse_with_focus (urwid.tests.test_vterm.TermTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/urwid-2.1.2/urwid/tests/test_vterm.py", line 254, in test_scrolling_region_reverse_with_focus
    self.expect('\n\nbbb\nXXX\n\naaa', focus=True)
  File "/build/urwid-2.1.2/urwid/tests/test_vterm.py", line 130, in expect
    self.assertEqual(got, what, desc)
AssertionError: b'\n\nbbb\n\n\naaa' != b'\n\nbbb\nXXX\n\naaa' : Expected:
b'\n\nbbb\nXXX\n\naaa'
Got:
b'\n\nbbb\n\n\naaa'

----------------------------------------------------------------------
Ran 311 tests in 1.819s

FAILED (failures=2)
Test failed: <unittest.runner.TextTestResult run=311 errors=0 failures=2>
error: Test failed: <unittest.runner.TextTestResult run=311 errors=0 failures=2>
```

**Comment by penguinolog** [comment]
resolved by #1176
