### ISSUE TITLE
Current default branch breaks khal

### ISSUE THREAD

**Issue by dvzrv** [urwid/urwid#548]
##### Description:
Building from latest commit on default branch (master) breaks khal.
As discussed on https://github.com/urwid/urwid/commit/9976f338c122a208b8a9108590ea525086cdd5a1 I am currently trying to find a commit of this project which works on Python 3.11 and does not break the consumers of this package (see downstream issue with Arch Linux: https://bugs.archlinux.org/task/78333).

##### Affected versions (if applicable)
`master` branch https://github.com/urwid/urwid/commit/1cc1d63358f7759785b39079eca069ed41078b6d (broken since at least https://github.com/urwid/urwid/commit/350ee5c47ff565d3b0d25b1c3cbddbfb2a0a2a4f)

##### Steps to reproduce (if applicable)
```sh
$ ikhal
Traceback (most recent call last):
  File "/usr/bin/ikhal", line 5, in <module>
    main_ikhal()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/cli.py", line 501, in interactive_cli
    controllers.interactive(
  File "/usr/lib/python3.11/site-packages/khal/controllers.py", line 591, in interactive
    pane = ui.ClassicView(
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/__init__.py", line 1065, in __init__
    calendar = CalendarWidget(
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 632, in __init__
    self.walker = CalendarWalker(
                  ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 363, in __init__
    weeks = self._construct_month(initial.year, initial.month)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 549, in _construct_month
    week = self._construct_week(week)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 511, in _construct_week
    week = DateCColumns(this_week,
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 139, in __init__
    super().__init__(widget_list, **kwargs)
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 2256, in __init__
    self.focus_position = focus_column
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 160, in _set_focus_position
    super()._set_focus_position(position)
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 243, in _set_focus_position
    self.focus_position = position
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 156, in _set_focus_position
    self._clear_cursor()
  File "/usr/lib/python3.11/site-packages/khal/ui/calendarwidget.py", line 145, in _clear_cursor
    old_pos = self.focus_position
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 229, in _get_focus_position
    return self.focus_position
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 229, in _get_focus_position
    return self.focus_position
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 229, in _get_focus_position
    return self.focus_position
           ^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 972 more times]
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 223, in _get_focus_position
    warnings.warn(
RecursionError: maximum recursion depth exceeded while calling a Python object
```

##### Expected/actual outcome
`ikhal` works.

**Comment by penguinolog** [comment]
Main issue in `khal`, itself, which override `focus_position` property back to call `_get_focus_position()` (deprecated, originally from pre-decorator era).
Fix will be done at few hours, BTW `khal` should not override private methods - only public methods and documented logic are public API.

**Comment by dvzrv** [comment]
Cool thank you! I will open a ticket for them as well and link here.

**Comment by dvzrv** [comment]
@penguinolog Much appreciated! :heart:
