### ISSUE TITLE
ikhal crashes when creating new event and using calendar other than default

### ISSUE THREAD

**Issue by dvzrv** [urwid/urwid#550]
##### Description:
With urwid built from bac20db87eaeb0b7a0026807d7e6dbe391b08580 I am seeing a crash with `ikhal` when trying to create a new event that is not using the default calendar.

##### Affected versions (if applicable)
`master` branch bac20db87eaeb0b7a0026807d7e6dbe391b08580

##### Steps to reproduce (if applicable)

Execute `ikhal` (with at least two separate calendars), create new event, try to add it to a different calendar than the default.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/khal/ui/__init__.py", line 1364, in start_pane
    loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 320, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 423, in _run
    self.event_loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 148, in run
    self._loop()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 180, in _loop
    self._entering_idle()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 137, in _entering_idle
    callback()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 621, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 635, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/wimp.py", line 665, in render
    self._update_overlay(size, focus)
  File "/usr/lib/python3.11/site-packages/urwid/wimp.py", line 641, in _update_overlay
    canv = self._original_widget.render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 1567, in render
    body = self.body.render((maxcol, maxrow-ftrim-htrim),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 2880, in render
    canv = w.render(sub_size, focus=focus and self.focus_position == i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 1835, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 1835, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/listbox.py", line 518, in render
    focus_canvas = focus_widget.render((maxcol,), focus=focus)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/container.py", line 2880, in render
    canv = w.render(sub_size, focus=focus and self.focus_position == i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget.py", line 149, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/wimp.py", line 625, in render
    canv.set_pop_up(self._pop_up_widget, **self.get_pop_up_parameters(size, focus))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Choice.get_pop_up_parameters() takes 1 positional argument but 3 were given
```

##### Expected/actual outcome
ikhal does not crash

**Comment by penguinolog** [comment]
Regression introduced in PR #480 , looking for the most correct way to fix (good feature, behavior not covered by urwid and khal tests)

**Comment by dvzrv** [comment]
Thanks! It works :tada:
