### ISSUE TITLE
getting UnicodeEncodeError when starting an urwid application with LANG set to an not-installed locale

### ISSUE THREAD

**Issue by fmoreau** [urwid/urwid#72]
Hello,

Here's the traceback:

Traceback (most recent call last):
  File "bin/app.py", line 153, in <module>
    main()
  File "bin/app.py", line 149, in main
    loop.run()
  File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/lib/python3.4/site-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 314, in _run
    self.draw_screen()
  File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 566, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/lib/python3.4/site-packages/urwid/raw_display.py", line 770, in draw_screen
    self._term_output_file.write(l)
UnicodeEncodeError: 'ascii' codec can't encode character '\u250c' in position 0: ordinal not in range(128)

Additionnal information:

urwid.set_encoding("utf8") is called before running the loop.

Appliction is started like this: "LANG=aa_DJ.UTF-8 python app.py" where aa_DJ locale is not installed.

**Comment by and3rson** [comment]
There have been recent updates to the locale handling and I could not reproduce this issue anymore.
