### ISSUE TITLE
patches from the Debian packaging

### ISSUE THREAD

**Issue by doko42** [urwid/urwid#728]
while updating the Debian package, I noticed some stuff is missing/wrong for building from the source tarball, the patches can be found at
https://salsa.debian.org/python-team/packages/urwid/-/tree/master/debian/patches?ref_type=heads

apply for 2.3.4 and 2.4.0.

- no-sphinx-changelog.diff: not relevant upstream, that sphinx extension is just not packaged for Debian
- tests-location.diff: correct the location of the tests
- version-module.diff: the source tarball is missing this, no idea how the extension works without that one

**Comment by penguinolog** [comment]
Specific for 2.4.0: it contains critical regressions and 2.4.1 will be published in few minutes.

About changes:

* Sphinx: better to pull git tags from `gh-pages` branch, it contains fully built HTML documentation with already generated changelog.
* Tests moved out of package: it's not needed for functionality and technically garbage for production environment, so it's not included in SDIST.
* `from urwid.version import version_tuple as __version_tuple__` - it's for cases, when `setuptools_scm` is old and enforced to not use isolated build environment. Newer versions of `setuptools_scm` produce `__version_tuple__` directly.
* `from __future__ import division, print_function` - this is totally not used, it was for python 2.7.
Now used only `from __future__ import annotations`.

**Comment by ulidtko** [comment]
@penguinolog debian packaging runs tests as part of build process. Yes, test scripts should not be included in the ultimate distribution package; that change is fine.

But `setup.py` still says `"test_suite": "urwid.tests"` which is incorrect, and breaks deb package build process (it runs tests). Still reviewing the other patches, but this one should land in mainline, IMO.

**Comment by penguinolog** [comment]
Setuptools deprecated tests running from `setup.py`:

> test is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use [tox](https://tox.readthedocs.io/).

**Comment by ulidtko** [comment]
Hey @doko42, thanks for bringing this up :pray: 

* `tests-location.diff` — pybuild debhelper claims to support testing with [tox](https://tox.wiki); please try `--test-tox` in `debian/rules`, or perhaps `export PYBUILD_TEST_TOX=1` (I'd also expect it may autodetect presence of `tox.ini`);

* `no-sphinx-changelog.diff` — seems like this will stay in debian/patches, as it's used in CI workflows in the mainline repo;

* `version-module.diff` — this one is generated from git at build-time. How do deb scripts approach this usually?

**Comment by ulidtko** [comment]
> we can't include pre-built stuff.

can you feasibly omit packaging the generated changelog then?

**Comment by penguinolog** [comment]
> > we can't include pre-built stuff.
> 
> can you feasibly omit packaging the generated changelog then? 

We can also lookup into autogeneration of change log source before release. Full writing of changelog is a pain and GitHub generation helps, but if it's a problem for end users - we can check for better solutions.

**Comment by doko42** [comment]
> > we can't include pre-built stuff.
> 
> can you feasibly omit packaging the generated changelog then?

yes, that's what I'm currently doing now

**Comment by yuzibo** [comment]
@doko42 
Hi, today I am packaging the package based on 2.3.4. I found if add `pybuild-plugin-pyproject and python3-setuptools-scm-git-archive` on d/control, it will generate version.py under urwid.  Thought `python3-setuptools-scm-git-archive` is  deprecated maybe.

**Comment by penguinolog** [comment]
`python3-setuptools-scm-git-archive` should be deprecated if `setuptools-scm` version is >= 7.0.
Starting from this version, all functionality is done by `setuptools-scm` itself

**Comment by penguinolog** [comment]
@doko42 I see you are cloned 2.4.0. Please update to 2.4.1 to get regressions fixes

**Comment by Hook25** [comment]
The new version of the package is copied over to Ubuntu without modification. It seems to me (please correct me if I'm wrong @yuzibo) that the [list of files](https://packages.ubuntu.com/noble/amd64/python3-urwid/filelist) is missing `display/_web.js` and `display/_web.css`. This makes the package "broken" given that any import of the `web.py` module will produce a `FileNotFoundError`. 

My best guess to why this is happening is that the `MANIFEST.in` file doesn't explicitly include these two files so they are excluded from the source build. I'm creating a small PR to fix this, if you agree this may be the problem we will also need to update the package soon.

See: 
```
root@noble:~# apt install python3-setuptools python3-urwid
[...]
Unpacking python3-urwid (2.4.1-0.2) ...
Setting up python3-urwid (2.4.1-0.2) ...
[...]
root@noble:~# python3
Python 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urwid.display.web
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/urwid/display/web.py", line 52, in <module>
    _js_code = CURRENT_DIR.joinpath("_web.js").read_text("utf-8")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/urwid/display/_web.js'
```

**Comment by penguinolog** [comment]
> EDIT: [Small PR here](https://github.com/urwid/urwid/pull/750)
Issue and PR accepted, checking if it's enough for correct packaging.

**Comment by penguinolog** [comment]
@Hook25 looks like modern packaging (`python -m build`) includes needed files already (I checked it) but was issue with another packaging tool.
After CI done, I'll merge PR.

**Comment by yuzibo** [comment]
@Hook25 you are right. From Debian [filelist](https://packages.debian.org/sid/amd64/python3-urwid/filelist), there are the same situation as you said with Ubuntu. Thanks for your fixing. I will package it on Debian if @doko42 do not have time to package it.

**Comment by penguinolog** [comment]
2.4.3 had regression in `Columns` render, which was urgently fixed in 2.4.4
@yuzibo @Hook25 @doko42
