### ISSUE TITLE
[BUG] urwid.Overlay valign doesn't accept `relative` any more

### ISSUE THREAD

**Issue by geier** [urwid/urwid#851]
##### Description:
urwid.Overlay's valign doesn't accept values of `('relative', 50)` any more, if though it should be fine according to [the documentation](https://urwid.org/reference/widget.html#overlay). This used to work until 2.4.2

##### Affected versions (if applicable)
- [X] `master` branch ead68bb158989b230ee845041747a0d04d462590
- [X] Latest stable version from `pypi`
- [X] 2.4.3 and onwards (haven't tested every release, but 2.4.2 still works)
##### Steps to reproduce (if applicable)
This example program used to work with older versions of urwid (<=2.4.2) but breaks with current versions.

```python
import urwid

text = urwid.Text("Hello, World!")
fill = urwid.Filler(text, 'top')

version = urwid.Text(f"This is urwid version: {urwid.__version__}")
filled = urwid.Filler(version, 'top')
overlay = urwid.Overlay(
    fill,
    filled,
    align='center',
    width=('relative', 60),
    valign=('relative', 50),
    height=('relative', 60),
)

loop = urwid.MainLoop(overlay)
loop.run()
```

```
Traceback (most recent call last):
  File "/Users/cg/workspace/khal/breaks.py", line 9, in <module>
    overlay = urwid.Overlay(
              ^^^^^^^^^^^^^^
  File "/Users/cg/workspace/khal/.venv/lib/python3.11/site-packages/urwid/widget/overlay.py", line 171, in __init__
    self.set_overlay_parameters(align, width, valign, height, min_width, min_height, left, right, top, bottom)
  File "/Users/cg/workspace/khal/.venv/lib/python3.11/site-packages/urwid/widget/overlay.py", line 527, in set_overlay_parameters
    self.options(
  File "/Users/cg/workspace/khal/.venv/lib/python3.11/site-packages/urwid/widget/overlay.py", line 430, in options
    VAlign(valign_type),
    ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: <WHSettings.RELATIVE: 'relative'> is not a valid VAlign
```

##### Expected/actual outcome
[...]

**Comment by penguinolog** [comment]
Fixed, added tests to prevent regression in the future and updated docstrings/typing annotations.
Made urgent release.

**Comment by geier** [comment]
Thank you very much for the incredibly quick fix and release!
