### ISSUE TITLE
[BUG] Test suite fails if `trio` is installed without `exceptiongroup`

### ISSUE THREAD

**Issue by mgorny** [urwid/urwid#893]
##### Description:
When `trio` is installed in the test environment but `exceptiongroup` is not, the test suite wrongly assumes that the dependencies for `TrioEventLoop` are met and the tests fail:

```pytb
======================================================================
ERROR: test_error (tests.test_event_loops.TrioEventLoopTest.test_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/urwid/tests/test_event_loops.py", line 371, in setUp
    self.evl = urwid.TrioEventLoop()
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/urwid/urwid/__init__.py", line 346, in __getattr__
    raise AttributeError(f"{name} not found in {__package__}")
AttributeError: TrioEventLoop not found in urwid. Did you mean: 'EventLoop'?

======================================================================
ERROR: test_event_loop (tests.test_event_loops.TrioEventLoopTest.test_event_loop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/urwid/tests/test_event_loops.py", line 371, in setUp
    self.evl = urwid.TrioEventLoop()
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/urwid/urwid/__init__.py", line 346, in __getattr__
    raise AttributeError(f"{name} not found in {__package__}")
AttributeError: TrioEventLoop not found in urwid. Did you mean: 'EventLoop'?

======================================================================
ERROR: test_remove_alarm (tests.test_event_loops.TrioEventLoopTest.test_remove_alarm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/urwid/tests/test_event_loops.py", line 371, in setUp
    self.evl = urwid.TrioEventLoop()
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/urwid/urwid/__init__.py", line 346, in __getattr__
    raise AttributeError(f"{name} not found in {__package__}")
AttributeError: TrioEventLoop not found in urwid. Did you mean: 'EventLoop'?

======================================================================
ERROR: test_remove_watch_file (tests.test_event_loops.TrioEventLoopTest.test_remove_watch_file)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/urwid/tests/test_event_loops.py", line 371, in setUp
    self.evl = urwid.TrioEventLoop()
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/urwid/urwid/__init__.py", line 346, in __getattr__
    raise AttributeError(f"{name} not found in {__package__}")
AttributeError: TrioEventLoop not found in urwid. Did you mean: 'EventLoop'?

======================================================================
ERROR: test_run (tests.test_event_loops.TrioEventLoopTest.test_run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/urwid/tests/test_event_loops.py", line 371, in setUp
    self.evl = urwid.TrioEventLoop()
               ^^^^^^^^^^^^^^^^^^^
  File "/tmp/urwid/urwid/__init__.py", line 346, in __getattr__
    raise AttributeError(f"{name} not found in {__package__}")
AttributeError: TrioEventLoop not found in urwid. Did you mean: 'EventLoop'?

----------------------------------------------------------------------
Ran 424 tests in 4.825s

FAILED (errors=5, skipped=23)
```

##### Affected versions (if applicable)
- [x] `master` branch (a1acea0aa49efbc86bfbf869739e0ee0663efc44)
- [x] Latest stable version from `pypi` (2.6.12)
- [ ] Other (specify source)

##### Steps to reproduce (if applicable)
```
pip install -e . trio
python -m unittest
```

Note that this needs to be done with new enough Python (e.g. 3.12), so that `exceptiongroup` isn't pulled as a dependency.

##### Expected/actual outcome
Tests passing, e.g. either skipping trio-related tests when `exceptiongroup`, and ideally not using `exceptiongroup` backport on newer Pythons where exception groups are natively supported.

**Comment by mgorny** [comment]
Thanks!
