### ISSUE TITLE
[BUG] set_alarm_in with callback type urwid.pile crashes urwid

### ISSUE THREAD

**Issue by emhamm** [urwid/urwid#914]
##### Description:
I run a urwid.MainLoop, quite a standard setup i would say. But if i set an alarm with callback type urwid.Pile urwid crashes every time.

```
Traceback (most recent call last):
  File "/usr/bin/myprogramm.py", line 34, in <module>
    loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 337, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 439, in _run
    self.event_loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 182, in run
    self._loop()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 229, in _loop
    record.data()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 284, in cb
    if callback(data) is False:
       ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lib/widgets/Progress.py", line 63, in _on_progress
    self.handle_done()
  File "/usr/lib/python3.11/site-packages/lib/widgets/Progress.py", line 37, in handle_done
    self.result.original_widget = DoClose.OnCallback(self.mainloop)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/lib/widgets/DoClose.py", line 18, in __init__
    mainloop.set_alarm_in(self.dt, self.on_alarm)
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 215, in set_alarm_in
    self.logger.debug(f"Setting alarm in {sec!r} seconds with callback {callback!r}")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 441, in __repr__
    return split_repr(self)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/split_repr.py", line 49, in split_repr
    alist = sorted((str(k), normalize_repr(v)) for k, v in self._repr_attrs().items())
                                                           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 245, in _repr_attrs
    attrs = {**super()._repr_attrs(), "focus_item": self.focus_position if len(self._contents) > 1 else None}
                                                                               ^^^^^^^^^^^^^^
AttributeError: 'DoClose' object has no attribute '_contents'. Did you mean: 'contents'?
```

##### Affected versions (if applicable)
- [x] `master` branch (specify commit)
- [x] Latest stable version from `pypi`
- [ ] Other (specify source)

this commit introduces the line which errors now: https://github.com/urwid/urwid/commit/38b4c7857557ca579a2f8f8e1ad356f832f0bc71

##### Steps to reproduce (if applicable)
in set_alarm_in set a callback of type urwid.Pile 

##### Expected/actual outcome
callback goes through, no crash happens :-)

**Comment by emhamm** [comment]
edit: broken since urwid v2.4.2

**Comment by emhamm** [comment]
in fact the updates triggers a bug in my code, closing.

sorry for the noise.
